### ISSUE TITLE
I don't change the wallpaper

### ISSUE THREAD

**Issue by AlphaTechnolog** [addy-dclxvi/i3-starterpack#17]
I am new in i3wm and i try change the wallpaper but it not change... in the `.config/i3/config`, the next line change the wallpaper but it not works:

```
exec --no-startup-id hsetroot -center /home/[USERNAME]/.wallpaper.png
```

in my `/home/[USERNAME]/` exists the file `.wallpaper.png` but it is not loaded. Help me please, the wallpaper displayed is the debian 9 default wallpaper. Help me please!!!

**Comment by addy-dclxvi** [comment]
There are several possibilities

- Make sure that hsetroot package is installed
- Make sure that the permission of the wallpaper file allowed to be read
- Make sure that the [USERNAME] is filled with your own username. Mine is
/home/addy/.wallpaper.png
- If the steps above did not work, please try to use other wallpaper
handling program like Nitrogen

**Comment by AlphaTechnolog** [comment]
Thanks the program `hsetroot` was not installed, i was installed it and reboot, and all is working... Thanks
