### ISSUE TITLE
Tztime local not visible.

### ISSUE THREAD

**Issue by Jocadbz** [addy-dclxvi/i3-starterpack#21]
After applying the default configs, tztime local isn't visible. It just stays a black space where it should display itself.
![2021-11-20-181731_1366x768_scrot](https://user-images.githubusercontent.com/83680590/142741193-ef8f8030-de8d-4bd1-bc33-99d459dd99bb.png)
(image)

**Comment by falzikla** [comment]
tztime local {
		format = "<span background='#81a1c1'>  %a %-d %b %H:%M </span>"
}

**Comment by sugan0tech** [comment]
Try doing single format specifier without extras, 
```
tztime local {
                format = "<span background='#81a1c1'>  %Y-%m-%d %H:%M:%S </span>"
}
```

**Comment by Jocadbz** [comment]
Yeah, it worked. Thank you.
